# Generated by Django 3.1.8 on 2021-08-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('expiration', models.DateField()),
                ('alert', models.BooleanField()),
            ],
        ),
    ]
